version: "3"

services:
  perfy.hub:
    depends_on:
      - db
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@db:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
    image: hasura/graphql-engine:v1.0.0-beta.2
    ports:
      - 8080:8080

  perfy.web:
    build:
      context: ./web
    command: yarn dev
    depends_on:
      - perfy.hub
      - perfy.authentication
    volumes:
      - ./web:/web-app
      - ./web/package.json:/web-app/package.json
      - ./web/yarn.lock:/web-app/yarn.lock
    ports:
      - "3000:3000"

  perfy.cron_lighthouse:
    build:
      context: ./cron-lighthouse
    command: yarn dev
    depends_on:
      - db
    volumes:
      - ./cron-lighthouse:/cron-lighthouse-app
      - ./cron-lighthouse/package.json:/cron-lighthouse-app/package.json
      - ./cron-lighthouse/yarn.lock:/cron-lighthouse-app/yarn.lock
    ports:
      - "3001:3001"

  perfy.authentication:
    build:
      context: ./authentication
    command: yarn dev
    depends_on:
      - db
    ports:
      - "3030:3030"
    volumes:
      - ./authentication:/authentication-app
      - ./authentication/package.json:/authentication-app/package.json
      - ./authentication/yarn.lock:/authentication-app/yarn.lock

  db:
    image: postgres:11.3-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
