version: "3"

services:
  perfy.hub:
    build:
      context: ./hub
    image: strapi/strapi
    environment:
      - APP_NAME=hub
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=hub
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=hub
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ./hub:/hub-app
      - /hub-app/node_modules
    depends_on:
      - db
    restart: always

  perfy.web:
    build:
      context: ./web
    command: yarn dev
    volumes:
      - ./web:/web-app
      - ./web/package.json:/web-app/package.json
      - ./web/yarn.lock:/web-app/yarn.lock
      - ./web-app/node_modules
    ports:
      - "3000:3000"
    restart: always

  perfy.cron_lighthouse:
    build:
      context: ./cron-lighthouse
    command: yarn dev
    volumes:
      - ./cron-lighthouse:/cron-lighthouse-app
      - ./cron-lighthouse/package.json:/cron-lighthouse-app/package.json
      - ./cron-lighthouse/yarn.lock:/cron-lighthouse-app/yarn.lock
      - ./cron-lighthouse-app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=hub
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always
