version: "3"

services:
  v1.hub:
    build:
      context: ./hub
    depends_on:
      - v1.db
    env_file: ./hub/.env
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./hub:/hub-app

  v1.web:
    build:
      context: ./web
    command: yarn dev
    depends_on:
      - v1.hub
      - v1.authentication
    volumes:
      - ./web:/web-app
      - ./web/package.json:/web-app/package.json
      - ./web/yarn.lock:/web-app/yarn.lock
    ports:
      - "3000:3000"

  v1.cron_lighthouse:
    build:
      context: ./cron-lighthouse
    command: yarn dev
    depends_on:
      - v1.db
    volumes:
      - ./cron-lighthouse:/cron-lighthouse-app
      - ./cron-lighthouse/package.json:/cron-lighthouse-app/package.json
      - ./cron-lighthouse/yarn.lock:/cron-lighthouse-app/yarn.lock
    ports:
      - "3001:3001"

  v1.authentication:
    build:
      context: ./authentication
    command: yarn dev
    env_file: ./authentication/.env
    depends_on:
      - v1.db
    ports:
      - "3030:3030"
    volumes:
      - ./authentication:/authentication-app
      - ./authentication/package.json:/authentication-app/package.json
      - ./authentication/yarn.lock:/authentication-app/yarn.lock

  v1.db:
    image: postgres:11.3-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
